- name: Bring up docker containers for docker connection inventory iface
  hosts: localhost
  pre_tasks: # run docker-stop.sh script to clean up old containers
    - name: Run docker-stop.sh script to clean up old containers
      command: ./docker-stop.sh
      args:
        chdir: "{{ playbook_dir }}"
  roles:
    - role: workshop_docker
      workshop_docker_names: "{{ groups['all'] }}"
      workshop_docker_image: "ownercz/docker-ubuntu2404-systemd"
- hosts: all
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python3 python3-minimal)
    - name: Check ansible deps
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - python3
        - python3-apt
        - lsb-release
    - name: Gather facts
      setup: # aka gather_facts
  tasks:
    - name: "Say hello to my new containers"
      ping:
